### ISSUE TITLE
Doubt regarding data preparation for unsupervised mask generation with TokenCut

### ISSUE THREAD

**Issue by sayakpaul** [hila-chefer/RobustViT#1]
What input images should be provided to the TokenCut script?

**Comment by hila-chefer** [comment]
Hi @sayakpaul, thanks for your interest!
the `img_path` parameter of the script should refer to the folder containing the images you wish to localize with TokenCut, and the `out_dir` parameter should refer to the folder to output the localization maps.  
In our paper, we used the same images segmented by ImageNet-S as our `img_path`  so that the comparison to the "unsupervised" case is fair.

I hope this answers your question, but please let me know if you require further clarification.

**Comment by sayakpaul** [comment]
It does. Thanks, Hila!
